/* Tests: spec/40-architecture/partition-layout.md */

#include <stdint.h>
#include "unity.h"
#include "memory_map.h"

void test_flash_regions_fit_in_2mb(void)
{
    TEST_ASSERT_EQUAL_HEX32(0x08000000, HEAD_1_BASE);
    TEST_ASSERT_EQUAL_HEX32(0x00001000, HEAD_1_LENGTH);
    TEST_ASSERT_EQUAL_HEX32(HEAD_1_BASE + HEAD_1_LENGTH, HEAD_2_BASE);
    TEST_ASSERT_EQUAL_HEX32(HEAD_2_BASE + HEAD_2_LENGTH, BL_BASE);
    TEST_ASSERT_EQUAL_HEX32(BL_BASE + BL_LENGTH, CM4_BASE);
    TEST_ASSERT_EQUAL_HEX32(CM4_BASE + CM4_LENGTH, BANK_B_BASE);
    TEST_ASSERT_EQUAL_HEX32(BANK_B_BASE + BANK_B_LENGTH, ROM_NVDM_BASE);
    TEST_ASSERT_EQUAL_HEX32(ROM_NVDM_BASE + ROM_NVDM_LENGTH, ROM_WIFI_TX_POWER_BASE);
    TEST_ASSERT_EQUAL_HEX32(
        ROM_WIFI_TX_POWER_BASE + ROM_WIFI_TX_POWER_LENGTH,
        ROM_FLASH_PAD_BASE);
    TEST_ASSERT_EQUAL_HEX32(ROM_FLASH_PAD_BASE + ROM_FLASH_PAD_LENGTH, FLASH_END);
}

void test_bank_sizes_match(void)
{
    TEST_ASSERT_EQUAL_HEX32(CM4_LENGTH, BANK_B_LENGTH);
    TEST_ASSERT_EQUAL_HEX32(0x000EE000, CM4_LENGTH); /* 952 KB */
}

void test_dual_image_ctrl_inside_bootloader(void)
{
    TEST_ASSERT_TRUE(DUAL_IMAGE_CTRL_BASE >= BL_BASE);
    TEST_ASSERT_TRUE(DUAL_IMAGE_CTRL_BASE < BL_BASE + BL_LENGTH);
}

void test_vram_window_for_mpu_layout(void)
{
    TEST_ASSERT_EQUAL_HEX32(0x10000000, VRAM_BASE);
}
