#!/usr/bin/env bash
# Embed gzipped admin UI into firmware — spec/30-processes/web-ui.md
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
OUT="${ROOT}/../../firmware/src/web_ui_gz.c"
GZ="${ROOT}/.web_ui_bundle.gz"
BUNDLE="${ROOT}/.web_ui_bundle.html"
LOGIC_INLINE="${ROOT}/.logic.inline.js"
trap 'rm -f "$GZ" "$BUNDLE" "$LOGIC_INLINE"' EXIT

sed 's/^export //' "${ROOT}/logic.mjs" > "$LOGIC_INLINE"

awk -v logic="$LOGIC_INLINE" '
  /<!-- INJECT_LOGIC -->/ {
    while ((getline line < logic) > 0) {
      print line
    }
    close(logic)
    next
  }
  { print }
' "${ROOT}/index.html" > "$BUNDLE"

gzip -9 -c "$BUNDLE" > "$GZ"

raw_bytes=$(wc -c < "$BUNDLE")
gz_bytes=$(wc -c < "$GZ")

{
  echo "/* Generated by tools/web/build.sh — do not edit. */"
  echo "#include <stddef.h>"
  echo "#include <stdint.h>"
  xxd -i "$GZ" | sed 's/unsigned char .*\[\]/const uint8_t g_web_ui_gz[]/; s/unsigned int .*_len/const size_t g_web_ui_gz_len/'
} > "$OUT"
echo "Wrote $OUT (${gz_bytes} bytes gzipped, ${raw_bytes} bytes raw html)"
