#!/usr/bin/env bash
# Embed gzipped admin UI into firmware — spec/30-processes/web-ui.md
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
OUT="${ROOT}/../../firmware/src/web_ui_gz.c"
GZ="${ROOT}/.web_ui_bundle.gz"
BUNDLE_RAW="${ROOT}/.web_ui_bundle.raw.html"
BUNDLE="${ROOT}/.web_ui_bundle.html"
LOGIC_INLINE="${ROOT}/.logic.inline.js"
HTML_MINIFIER_VERSION="${HTML_MINIFIER_VERSION:-7.2.0}"
trap 'rm -f "$GZ" "$BUNDLE" "$BUNDLE_RAW" "$LOGIC_INLINE"' EXIT

sed 's/^export //' "${ROOT}/logic.mjs" > "$LOGIC_INLINE"

awk -v logic="$LOGIC_INLINE" '
  /<!-- INJECT_LOGIC -->/ {
    while ((getline line < logic) > 0) {
      print line
    }
    close(logic)
    next
  }
  { print }
' "${ROOT}/index.html" > "$BUNDLE_RAW"

raw_bytes=$(wc -c < "$BUNDLE_RAW")
gz_raw_bytes=$(gzip -9 -c "$BUNDLE_RAW" | wc -c)

if [ "${WEB_UI_SKIP_MINIFY:-}" = "1" ]; then
  cp "$BUNDLE_RAW" "$BUNDLE"
else
  npx --yes "html-minifier-terser@${HTML_MINIFIER_VERSION}" \
    --collapse-whitespace \
    --remove-comments \
    --minify-css true \
    --minify-js true \
    "$BUNDLE_RAW" -o "$BUNDLE"
fi

gzip -9 -c "$BUNDLE" > "$GZ"

min_raw_bytes=$(wc -c < "$BUNDLE")
gz_bytes=$(wc -c < "$GZ")

{
  echo "/* Generated by tools/web/build.sh — do not edit. */"
  echo "#include <stddef.h>"
  echo "#include <stdint.h>"
  xxd -i "$GZ" | sed 's/unsigned char .*\[\]/const uint8_t g_web_ui_gz[]/; s/unsigned int .*_len/const size_t g_web_ui_gz_len/'
} > "$OUT"
echo "Wrote $OUT (${gz_bytes} bytes gzipped minified, ${gz_raw_bytes} bytes gzipped unminified, ${raw_bytes} → ${min_raw_bytes} bytes raw)"
